name = "LibTrixi"
uuid = "7e097bd5-a775-4bc1-90b6-ad92bd7220c1"
authors = ["Michael Schlottke-Lakemper <michael@sloede.com>", "Benedict Geihe <bgeihe@uni-koeln.de>"]
version = "0.1.0"

[compat]
julia = "1.8"
