name = "LibTrixi"
uuid = "7e097bd5-a775-4bc1-90b6-ad92bd7220c1"
authors = ["Michael Schlottke-Lakemper <michael@sloede.com>", "Benedict Geihe <bgeihe@uni-koeln.de>"]
version = "0.1.0"

[deps]
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Trixi = "a7f1ee26-1774-49b1-8366-f1abc58fbfcb"

[compat]
julia = "1.8"
OrdinaryDiffEq = "6.53.2"
Trixi = "0.5.29"

[preferences.OrdinaryDiffEq]
PrecompileAutoSpecialize = false
PrecompileAutoSwitch = false
PrecompileDefaultSpecialize = true
PrecompileFunctionWrapperSpecialize = false
PrecompileLowStorage = true
PrecompileNoSpecialize = false
PrecompileNonStiff = true
PrecompileStiff = false
