name: Documentation

on:
  push:
    branches:
      - 'main'
    tags: '*'
    paths-ignore:
      - '.zenodo.json'
      - '.github/workflows/ci.yml'
      - '.github/workflows/CompatHelper.yml'
      - '.github/workflows/TagBot.yml'
  pull_request:
    paths-ignore:
      - '.zenodo.json'
      - '.github/workflows/ci.yml'
      - '.github/workflows/CompatHelper.yml'
      - '.github/workflows/TagBot.yml'
  workflow_dispatch:

# Cancel redundant CI tests automatically
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docs:
    runs-on: ubuntu-latest
    outputs:
      doxygen_dir: ${{ steps.determine_doxygen_dir.outputs.doxygen_dir }}
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.9'
          show-versioninfo: true
      - uses: julia-actions/julia-buildpkg@v1
        with:
          project: 'LibTrixi.jl'
        env:
          PYTHON: ""
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=joinpath(pwd(), "LibTrixi.jl"))); Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
          GKSwstype: 100 # To make GitHub Action work, disable showing a plot window with the GR backend of the Plots package
        run: julia --project=docs --color=yes docs/make.jl
      - name: Determine folder for doxygen docs
        id: determine_doxygen_dir
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required to determine directory
        run: |
          doxygen_dir=$(julia --project=docs --color=yes docs/determine_doxygen_dir.jl)
          echo "doxygen_dir=$doxygen_dir"
          echo "doxygen_dir=$doxygen_dir" >> "$GITHUB_OUTPUT"

  build-doxygen:
    runs-on: ubuntu-latest
    needs: build-docs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install doxygen
        run: |
          sudo apt-get install -y doxygen
      - name: Build doxygen docs
        run: |
          cd docs/doxygen
          doxygen
      - name: Deploy doxygen docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./docs/doxygen/build/html
          destination_dir: ${{ needs.build-docs.outputs.doxygen_dir }}
